language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t neerjgoyal87/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true neerajgoyal87/docker-react npm run test